# This workflow will automatically create a matching Release in GitHub after the Maven release has pushed a tag to the repository.

on:
  push:
    tags:
      - 'v*' # Tags matching v*, e.g. v1.0.0

name: Create GitHub Release when tag is pushed

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false